global using MediatR;
global using MicroRabbit.Banking.Api;
global using MicroRabbit.Banking.Application.Interfaces;
global using MicroRabbit.Banking.Data.Context;
global using MicroRabbit.Banking.Domain.Models;
global using MicroRabbit.Infra.IoC;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.Reflection;